export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const UPLOAD_CONTENT_BEGIN = "UPLOAD_CONTENT_BEGIN";
export const UPLOAD_CONTENT_SUCCESS = "UPLOAD_CONTENT_SUCCESS";
export const UPLOAD_CONTENT_ERROR = "UPLOAD_CONTENT_ERROR";
