export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const UPLOAD_CONTENT_BEGIN = "UPLOAD_CONTENT_BEGIN";
export const UPLOAD_CONTENT_SUCCESS = "UPLOAD_CONTENT_SUCCESS";
export const UPLOAD_CONTENT_ERROR = "UPLOAD_CONTENT_ERROR";

export const UPDATE_PASSWORD_BEGIN = "UPDATE_PASSWORD_BEGIN";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";
export const GET_CONTENT_BEGIN = "GET_CONTENT_BEGIN";
export const GET_CONTENT_SUCCESS = "GET_CONTENT_SUCCESS";
export const GET_CONTENT_ERROR = "GET_CONTENT_ERROR";

export const CHECK_VALUES_BEGIN = "CHECK_VALUES_BEGIN";
export const CHECK_VALUES_SUCCESS = "CHECK_VALUES_SUCCESS";
export const CHECK_VALUES_ERROR = "CHECK_VALUES_ERROR";

export const TOGGLE_CATEGORY = "TOGGLE_CATEGORY";
export const TOGGLE_MISTAKES = "TOGGLE_MISTAKES";
export const CLEAR_USER_TEXT = "CLEAR_USER_TEXT";
export const USER_TEXT = "USER_TEXT";

